config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	root to: "products#index"
  resources :users
  # resources :images
  # resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :products, except: [:edit, :index, :create, :show, :new, :update, :destroy] do
      	collection do
	      	post '/' => 'products#create'
	      	put '/' => 'products#update'
	      	get '/' => 'products#index'
	      end
      end
    end
  end

  namespace :admin do
    resources :products, except: [:create, :show, :new, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :images

	serialize :tags, Array
	serialize :categories, Array
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	enum role: ["admin","general_user"]

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:update, :edit]

  def index
    @products = Product.page(params[:page]).per(25).order('id DESC')
    @user = current_user
  end

  def edit
    @product
  end


  ###ASSUMPTIONS
  #  Tags and Categories are separated by space when editing
  ###
  def update
    categories = product_params["categories"].split(" ").map {|item| item.squish()}
    tags = product_params["tags"].split(" ").map {|item| item.squish()}
    processed_params = product_params.merge({"categories" => categories, "tags" => tags})
    respond_to do |format|
      if @product.update(processed_params)
        format.html { redirect_to admin_products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_product
      # binding.pry
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :sku_id, :categories, :tags, :price, :expire_date)
    end
end

app/controllers/api/v1/images_controller.rb
class Api::V1::ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:img_path)
    end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApiController
  before_action :set_product, only: [:update, :create]


  ###ASSUMPTIONS
  #  Triggers When a POST request with body is triggered
  ###
  def create
    if product_params.present?
      if @product.nil?
        @new_product = Product.new(product_params.except("images"))
          if @new_product.save
            product_params["images"].each do |img_obj|
              Image.create({"img_path" => img_obj["img_path"], "product_id" => @new_product.id})
            end
            render status: 200, json: {"message" => "successfully created"} and return
          else
            render status: 500, json: {"message" => "#{@product.errors}" } and return
          end
      else
        render :update
      end

    else
      render status: 422, json: {"message" => "Improper Format"} and return
    end
  end

  ###ASSUMPTIONS
  #  When a get request with body is triggered
  #  Check for method in json and process accordingly
  ###

  def index
    method_passed = params.fetch("method", "").upcase
    case method_passed
      when ""
        render status: 422, json: {"message" => "No Method Defined"} and return
      when "POST"
        render :create
      when "PUT"
        render :update
      else
        render status: 422, json: {"message" => "Method out of scope"} and return
      end
  end

  ###ASSUMPTIONS
  #  Triggers When a PUT request with body is triggered
  ###
  def update
    if @product
      @product.attributes = product_params.except("images")
      if @product.changed?
        if @product.save
          render status: 200, json: {"message" => "successfully updated"} and return
        else
          render status: 500, json: {"message" => "#{@product.errors}" } and return
        end
      else
        render status: 304, json: {"message" => "No new data to save"} and return
      end
    else
      render :create
    end
  end

  private

    ###ASSUMPTION
    #  Product is assumed to be unique if the combination of
    #  Name, Price and SKU Id is unique
    #####
    def set_product
      # @product = Product.find(:all, :conditions => ['name LIKE ? AND price LIKE ? AND sku_id LIKE ?', "%#{product_params.fetch('name', 'NULL')}%", "%#{product_params.fetch('price', 'NULL')}%", "%#{product_params.fetch('sku_id', 'NULL')}%"])
      @product = Product.where('name LIKE :name AND price LIKE :price AND sku_id LIKE :sku_id', name: "%#{product_params.fetch('name', 'NULL')}%", price: "%#{product_params.fetch('price', 'NULL')}%", sku_id: "%#{product_params.fetch('sku_id', 'NULL')}%").first

    end

    def product_params
      params.require(:parameters).permit(:name, :sku_id, {categories: []}, {tags: []}, {images: [:img_path]}, :price, :expire_date)
    end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :mobile, :password, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/_form.html.erb
<%= form_for(@product, url: admin_product_path(), method: :put, html: { class: ""}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :sku_id %>
    <%= f.number_field :sku_id %>
  </div>

  <div class="field">
    <%= f.label :categories %>
    <%= f.text_field :categories %>
  </div>

  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tags %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :expire_date %>
    <%= f.datetime_select :expire_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<% if @user.role == "admin" %>

<h1>Editing Product</h1>

<%= render 'form' %>

<% else %>

<h1 style="color: red;">Unauthorized access!</h1>

<% end %>

app/views/admin/products/index.html.erb
<% if @user.role == "admin" %>

<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sku</th>
      <th>Price</th>
      <th colspan="5">Images</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, edit_admin_product_path(product) %></td>
        <td><%= product.sku_id %></td>
        <td><%= product.price %></td>
        <% product.images.pluck('img_path').each do |path| %>
        <!-- <td><img src="#{path}", width="50" , height="50"></img></td> -->
        <td><%= image_tag "#{path}", width: "50px", height: "50px" %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @products %>

<% else %>

<h1 style="color: red;">Unauthorized access!</h1>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thrill</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end%>
    <% if alert %>
      <p class="alert alert-danger"><%= alert%></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :mobile %>
    <%= f.text_field :mobile %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :role %>
    <%= f.number_field :role %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>